# name: The Deploy

# on:
#   push:
#     branches: [master, preprod]
# jobs:
#   test_pull_request:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v1
#         with:
#           node-version: 12
#       - run: npm ci
#       # - run: npm test
#       - run: npm run build --prod
#       - uses: w9jds/firebase-action@master
#         with:
#           args: deploy --only hosting
#         env:
#           FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}

name: pull_request_on_master

on:
  pull_request:
    branches: [master, preprod]
jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Super-Linter
        uses: super-linter/super-linter@v.8.3.2
      # - uses: actions/setup-node@v1
      #   with:
      #     node-version: 12

      # - run: npm ci
      # - run: npm test
      # - run: npm run build


# name: Node CI

# on:
#   pull_request:
#     branches: [master, preprod]
# jobs:
#   test_pull_request:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v1
#         with:
#           node-version: 12
#       - run: npm ci
#       # - run: npm test
#       - run: npm run build


